# pytorch tensors

## goals

- different types of tensors in pytorch, and their properties
- creating tensors
- operations on tensors
- indexing, slicing, reshaping, joining, mutating

## Tensor data-type

### creating tensors

In [8]:
import torch
import numpy as np
import pandas as pd

- from sequenced data-types

In [22]:
# One-dimensional tensors
t1 = torch.Tensor([1, -2, 3])
t2 = torch.Tensor(np.array([1, -2, 3]))
t3 = torch.Tensor(pd.Series([1, -2, 3]))

# Two-dimensional tensors
t4 = torch.Tensor([[1, -2, 3], [4, 5, 6]])
t5 = torch.Tensor(np.array([[1, -2, 3], [4, 5, 6]]))

try:
    t6 = torch.Tensor(pd.DataFrame([[1, -2, 3], [4, 5, 6]]))
except ValueError as e:
    print('Error when calling a DataFrame directy:', e)

# Bigger-dimensional tensors
t7 = torch.Tensor([[[1, -2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Error when calling a DataFrame directy: expected sequence of length 2 at dim 0 (got 3)


- from constants

In [29]:
t_zeros = torch.zeros(2, 3)             
t_ones = torch.ones(2, 3)
t_eye = torch.eye(3)
t_range = torch.arange(0, 3, 0.5)
t_linspace = torch.linspace(0, 3, 6)

- from random number generators

In [172]:
# uniform
t_uniform_con = torch.rand(2, 3)
t_uniform_int = torch.randint(0, 10, (2, 3))

# normal
t_unit_normal = torch.randn(2, 3)
t_normal_same_mean_std = torch.normal(1., 2., size=(2, 3))
t_normal_same_mean = torch.normal(mean=3., std=torch.arange(1., 6.))
t_normal_same_std = torch.normal(mean=torch.arange(1., 6.), std=3.)

# bernoulli, binomial, categorical
t_bernoulli = torch.bernoulli(torch.tensor([0.3, 0.6, 0.5]))
t_binomial = torch.binomial(torch.tensor([10., 10., 10.]), torch.tensor([0.3, 0.6, 0.5]))
t_categorical = torch.multinomial(torch.tensor([0.3, 0.6, 0.3]), 5, replacement=True)

# others
t_dirichlet = torch.distributions.dirichlet.Dirichlet(torch.tensor([0.3, 0.6, 0.3])).sample()
t_exponential = torch.distributions.exponential.Exponential(torch.tensor([1.0, 2.0])).sample()
t_gamma = torch.distributions.gamma.Gamma(torch.tensor([1.0, 2.0]), torch.tensor([1.0, 2.0])).sample()
t_laplace = torch.distributions.laplace.Laplace(torch.tensor([1.0, 2.0]), torch.tensor([1.0, 2.0])).sample()
t_multivariate_normal = torch.distributions.multivariate_normal.MultivariateNormal(torch.tensor([1.0, 2.0]), torch.eye(2)).sample()
t_poisson = torch.distributions.poisson.Poisson(torch.tensor([1.0, 2.0])).sample()


- from other tensors

In [196]:
t1 = torch.Tensor([1, -2, 3])
t2 = torch.Tensor([[1, -2, 3], [4, 5, 6]])

# contants of same shape
t_zeros = torch.zeros_like(t1)
t_ones = torch.ones_like(t1)
t_rand = torch.rand_like(t1)

# dual matrices
t_transposed = t1.t()
t_diag = t1.diag()
t_inverse = t_diag.inverse()

# 

- from reshaping

- from slicing

- from composing

### data-types of numbers

Available data types include:
- `torch.bool`
- `torch.int8`
- `torch.uint8`
- `torch.int16`
- `torch.int32`
- `torch.int64`
- `torch.half`
- `torch.float`
- `torch.double`
- `torch.bfloat`

## Operations on tensors

### basic operations

- tensors and numbers

In [180]:
t1 - 3, t1 * 3, t1 / 3, t1 ** 3

(tensor([-2., -5.,  0.]),
 tensor([ 3., -6.,  9.]),
 tensor([ 0.3333, -0.6667,  1.0000]),
 tensor([ 1., -8., 27.]))

In [181]:
t1.sub(3), t1.mul(3), t1.div(3), t1.pow(3)

(tensor([-2., -5.,  0.]),
 tensor([ 3., -6.,  9.]),
 tensor([ 0.3333, -0.6667,  1.0000]),
 tensor([ 1., -8., 27.]))

- between tensors of same shape

In [182]:
t1 - t2, t1 * t2, t1 / t2, t1 ** t2

t1.sub(t2), t1.mul(t2), t1.div(t2), t1.pow(t2)

(tensor([-3., -7., -3.]),
 tensor([  4., -10.,  18.]),
 tensor([ 0.2500, -0.4000,  0.5000]),
 tensor([  1., -32., 729.]))

- between 2-dimensional tensors

In [197]:
t3 = torch.Tensor([[1, 2, 3], [4, 5, 6]])

t3 @ t3.T

tensor([[14., 32.],
        [32., 77.]])

- between tensors of different shapes (broadcasting)

In [201]:
t1 = torch.Tensor([1, -2, 3])
t2 = torch.Tensor([[1, -2, 3], [4, 5, 6]])

t1 - t2, t1 * t2, t1 / t2, t1 ** t2

(tensor([[ 0.,  0.,  0.],
         [-3., -7., -3.]]),
 tensor([[  1.,   4.,   9.],
         [  4., -10.,  18.]]),
 tensor([[ 1.0000,  1.0000,  1.0000],
         [ 0.2500, -0.4000,  0.5000]]),
 tensor([[ 1.0000e+00,  2.5000e-01,  2.7000e+01],
         [ 1.0000e+00, -3.2000e+01,  7.2900e+02]]))